app:
  use-queue: true
  database-access-type: jdbc
  gitUrl: https://api.github.com/
  stackUrl: https://api.stackexchange.com/2.3
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  retry:
    trigger: server-client
    strategy: const
    max-attempts: 3
    delay: 5
    statuses: 400, 401, 402, 403, 404, 500, 501, 502, 503, 504
  bucket:
    refill: 5
    capacity: 10
    timeout: 1

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
      url: jdbc:postgresql://localhost:5432/scrapper
      username: postgres
      password: postgres
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.value.default.type: dto.request.LinkUpdateRequest
    bootstrapServers: localhost:29092




server:
  port: 8000

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
