app:
  gitUrl: https://api.github.com/
  stackUrl: https://api.stackexchange.com/2.3
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

server:
  port: 8000

logging:
  config: classpath:log4j2-plain.xml
