global:
  scrape_interval: 20s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["host.docker.internal:8081","host.docker.internal:8082"]
